// data.js — shared painting data
// Artist: Somaye Minaei · signed "S. Minaei"
const PAINTINGS = [
  {
    slug: "floral-shirt",
    number: 8,
    title: "Lost in Thought",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "50 × 60 cm",
    subject: "Portrait Studies",
    series: "Portraits",
    image: "assets/paintings/floral-shirt.jpg",
    hero:  "assets/paintings-hero/floral-shirt.jpg",
    thumb: "assets/paintings-thumb/floral-shirt.jpg",
    detail: "assets/paintings/floral-shirt.jpg",
    square: "assets/paintings/floral-shirt.jpg",
    available: false,
    note: "A portrait of a woman in a floral blue dress. The moment when someone drifts into their own thoughts — a gaze that is present, but a mind that is somewhere else.",
    progress: [
      "Grisaille underpainting for the face",
      "Warm mid-tones in the hair and skin",
      "Dress painted wet-into-wet in a single session",
      "Floral pattern last — tiny marks, no drawing",
    ],
  },
  {
    slug: "candle-veil",
    number: 7,
    title: "Flame of Hope",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    subject: "Portrait Studies",
    series: "Light Studies",
    image: "assets/paintings/candle-veil.jpg",
    hero:  "assets/paintings-hero/candle-veil.jpg",
    thumb: "assets/paintings-thumb/candle-veil.jpg",
    detail: "assets/paintings/candle-veil.jpg",
    square: "assets/paintings/candle-veil.jpg",
    available: false,
    note: "A portrait of a young girl in the warm glow of a candle. What I was after in this piece was the play of light and shadow — a small flame pulling a face out of the darkness, creating a feeling somewhere between calm and unease.",
    progress: [
      "Dark ground — ivory black thinned with walnut oil",
      "Warm underpainting — burnt sienna and yellow ochre on the lit side",
      "Cool shadow — ultramarine glazed into the brown",
      "Flame last — lead white over a single transparent yellow",
    ],
  },
  {
    slug: "monument-valley",
    number: 6,
    title: "Red Valley",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    subject: "Landscape",
    series: "Walks",
    image: "assets/paintings/monument-valley.jpg",
    hero:  "assets/paintings-hero/monument-valley.jpg",
    thumb: "assets/paintings-thumb/monument-valley.jpg",
    detail: "assets/paintings/monument-valley.jpg",
    square: "assets/paintings/monument-valley.jpg",
    available: false,
    note: "A landscape of the red sandstone formations of Monument Valley. The vastness of these rocks and the depth of the space between them — that's what drew me in.",
    progress: [
      "Sky first — blue laid in thin, deepening toward the top",
      "Rock forms blocked in with raw sienna and burnt umber",
      "Shadow faces deepened — violet glazed into the warm red",
      "Foreground last — lighter and cooler, pulling the eye into the distance",
    ],
  },
  {
    slug: "tree-on-rock",
    number: 5,
    title: "Rooted in Stone",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "18 × 24 cm",
    subject: "Landscape",
    series: "Walks",
    image: "assets/paintings/tree-on-rock.jpg",
    hero:  "assets/paintings-hero/tree-on-rock.jpg",
    thumb: "assets/paintings-thumb/tree-on-rock.jpg",
    detail: "assets/paintings/tree-on-rock.jpg",
    square: "assets/paintings/tree-on-rock.jpg",
    available: false,
    note: "A lone tree on top of a rocky hill. Not out of necessity — as if it chose to be there and put down its roots.",
    progress: [
      "Sky laid in first — pale blue-grey, thin and even",
      "Rock mass blocked in with raw umber and titanium white",
      "Tree built up from the trunk — dark silhouette against the open sky",
      "Final texture added with short broken strokes for bark and foliage",
    ],
  },
  {
    slug: "statue",
    number: 4,
    title: "The Sculpture",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    subject: "Portrait Studies",
    series: "Portraits",
    image: "assets/paintings/statue.jpg",
    hero:  "assets/paintings-hero/statue.jpg",
    thumb: "assets/paintings-thumb/statue.jpg",
    detail: "assets/paintings/statue.jpg",
    square: "assets/paintings/statue.jpg",
    available: false,
    note: "A painting of a classical female bust. The precise light and shadow on the stone surface blurs the line between painting and sculpture.",
    progress: [
      "Cool grey ground — ivory black and titanium white",
      "Mass of the head blocked in with raw umber",
      "Half-tones built up in cool greys and warm whites",
      "Final shadows kept transparent — a single glaze of umber",
    ],
  },
  {
    slug: "sea-wildflowers",
    number: 3,
    title: "A Sunny Day",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "18 × 24 cm",
    subject: "Landscape",
    series: "Walks",
    image: "assets/paintings/sea-wildflowers.jpg",
    hero:  "assets/paintings-hero/sea-wildflowers.jpg",
    thumb: "assets/paintings-thumb/sea-wildflowers.jpg",
    detail: "assets/paintings/sea-wildflowers.jpg",
    square: "assets/paintings/sea-wildflowers.jpg",
    available: false,
    note: "A coastal landscape with wildflowers in the foreground. Blue sky, white clouds and a calm sea — a simple picture of a carefree day.",
    progress: [
      "Sky painted first — blue at the top, warm white toward the horizon",
      "Sea and far shore in one flat soft stroke",
      "Clouds shaped wet-into-wet before the sky dried",
      "Wildflowers last — small dabs of colour, worked quickly before the light changed",
    ],
  },
  {
    slug: "daisies-in-glass",
    number: 2,
    title: "Three Daisies",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "30 × 40 cm",
    subject: "Still Life",
    series: "Pigment Studies",
    image: "assets/paintings/daisies.JPG",
    hero:  "assets/paintings-hero/daisies.jpg",
    thumb: "assets/paintings-thumb/daisies.jpg",
    detail: "assets/paintings/daisies.JPG",
    square: "assets/paintings/daisies.JPG",
    available: false,
    note: "Three daisies in a simple glass bottle. Sometimes the simplest things, when truly seen, are enough.",
    progress: [
      "Teal ground — laid flat and left to dry",
      "Glass bottle first — the transparency built up in thin layers",
      "Stems painted through the glass, slightly shifted and greyed",
      "Daisies last — white over white, each petal shaped with a single stroke",
    ],
  },
  {
    slug: "yellow-branches",
    number: 1,
    title: "Golden Blossoms",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "50 × 40 cm",
    subject: "Still Life",
    series: "Pigment Studies",
    image: "assets/paintings/yellow-branches.jpg",
    hero:  "assets/paintings-hero/yellow-branches.jpg",
    thumb: "assets/paintings-thumb/yellow-branches.jpg",
    detail: "assets/paintings/yellow-branches.jpg",
    square: "assets/paintings/yellow-branches.jpg",
    available: false,
    note: "A still life of yellow-budded branches in an earthenware vase. The warmth of yellow against the cool background — two different moods in one frame.",
    progress: [
      "Warm ochre ground — laid flat and left to dry",
      "Vase massed in first — the darkest darks established early",
      "Branches painted one by one, each loaded with cadmium yellow",
      "Background drifted from warm to cool in a single long pass with a wide brush",
    ],
  },
];

const SERIES = [
  { slug: "portraits", title: "Portraits", count: 11, years: "2024 — present",
    summary: "Painted from life over multiple sittings. Grisaille underpainting, warm half-tones, the kind of slow looking only a willing sitter allows." },
  { slug: "light-studies", title: "Light Studies", count: 6, years: "2024 — present",
    summary: "Figures and objects under single sources — candle, window, lamp. One light; everything else is answer." },
  { slug: "walks", title: "Walks", count: 14, years: "2024 — present",
    summary: "Landscapes carried home from trips and long afternoons. Small panels on site; larger canvases finished in the studio." },
  { slug: "pigment-studies", title: "Pigment Studies", count: 5, years: "2024 — present",
    summary: "One-colour or two-colour studies, mostly still life. An exercise in how far a single tube will stretch before the eye needs help." },
];

window.PAINTINGS = PAINTINGS;
window.SERIES = SERIES;
