// data.js — shared painting data
// Artist: Somaye Minaei · signed "S. Minaei"
const PAINTINGS = [
  {
    slug: "floral-shirt",
    number: 8,
    title: "Lost in Thought",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "50 × 60 cm",
    subject: "Portrait Studies",
    series: "Portraits",
    image: "assets/paintings/floral-shirt.jpg",
    hero:  "assets/paintings-hero/floral-shirt.jpg",
    thumb: "assets/paintings-thumb/floral-shirt.jpg",
    detail: "assets/paintings/floral-shirt.jpg",
    square: "assets/paintings/floral-shirt.jpg",
    details: [
      "assets/paintings-detail/floral-shirt-1.jpg",
      "assets/paintings-detail/floral-shirt-2.jpg",
      "assets/paintings-detail/floral-shirt-3.jpg",
    ],
    available: false,
    note: "I've always been drawn to the moment just before someone comes back to the room — when the eyes are open but the mind has slipped somewhere private. I found that in her. She wasn't posing. She had simply forgotten I was there, and I stayed very still and painted as quietly as I could.",
  },
  {
    slug: "candle-veil",
    number: 7,
    title: "Flame of Hope",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    subject: "Portrait Studies",
    series: "Light Studies",
    image: "assets/paintings/candle-veil.jpg",
    hero:  "assets/paintings-hero/candle-veil.jpg",
    thumb: "assets/paintings-thumb/candle-veil.jpg",
    detail: "assets/paintings/candle-veil.jpg",
    square: "assets/paintings/candle-veil.jpg",
    details: [
      "assets/paintings-detail/candle-veil-1.jpg",
      "assets/paintings-detail/candle-veil-2.jpg",
      "assets/paintings-detail/candle-veil-3.jpg",
    ],
    available: false,
    note: "One evening I lit a single candle and watched what it did to the faces in the room — how it chose what to show and what to keep. I wanted to paint that choosing. There is something in a flame that feels like hope: small, warm, alive, and entirely uncertain.",
  },
  {
    slug: "monument-valley",
    number: 6,
    title: "Red Valley",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    subject: "Landscape",
    series: "Walks",
    image: "assets/paintings/monument-valley.jpg",
    hero:  "assets/paintings-hero/monument-valley.jpg",
    thumb: "assets/paintings-thumb/monument-valley.jpg",
    detail: "assets/paintings/monument-valley.jpg",
    square: "assets/paintings/monument-valley.jpg",
    details: [
      "assets/paintings-detail/monument-valley-1.jpg",
      "assets/paintings-detail/monument-valley-2.jpg",
      "assets/paintings-detail/monument-valley-3.jpg",
    ],
    available: false,
    note: "Standing in front of those cliffs I felt the particular smallness that comes not from being diminished but from being placed — the earth telling you, quietly, how long it has been here. I went home and tried to mix the exact red. It took a long time. The colour of very old stone is not one colour at all.",
  },
  {
    slug: "tree-on-rock",
    number: 5,
    title: "Rooted in Stone",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "18 × 24 cm",
    subject: "Landscape",
    series: "Walks",
    image: "assets/paintings/tree-on-rock.jpg",
    hero:  "assets/paintings-hero/tree-on-rock.jpg",
    thumb: "assets/paintings-thumb/tree-on-rock.jpg",
    detail: "assets/paintings/tree-on-rock.jpg",
    square: "assets/paintings/tree-on-rock.jpg",
    details: [
      "assets/paintings-detail/tree-on-rock-1.jpg",
      "assets/paintings-detail/tree-on-rock-2.jpg",
      "assets/paintings-detail/tree-on-rock-3.jpg",
    ],
    available: false,
    note: "There was no reason for it to grow there. No shelter, no soil to speak of — just bare rock at the top of a hill. And yet it had put itself down and stayed. I painted it because I recognised something in that. The stubbornness of growing in the wrong place, and doing it anyway.",
  },
  {
    slug: "statue",
    number: 4,
    title: "The Sculpture",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    subject: "Portrait Studies",
    series: "Portraits",
    image: "assets/paintings/statue.jpg",
    hero:  "assets/paintings-hero/statue.jpg",
    thumb: "assets/paintings-thumb/statue.jpg",
    detail: "assets/paintings/statue.jpg",
    square: "assets/paintings/statue.jpg",
    details: [
      "assets/paintings-detail/statue-1.jpg",
      "assets/paintings-detail/statue-2.jpg",
      "assets/paintings-detail/statue-3.jpg",
    ],
    available: false,
    note: "She had been standing in a museum for two hundred years, perfectly still, and everyone who passed her was moving. I wondered what it would mean to paint something that was already a portrait — to look at a face that had already been looked at so carefully, and find something in it that the sculptor left for oil paint to say.",
  },
  {
    slug: "sea-wildflowers",
    number: 3,
    title: "A Sunny Day",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "18 × 24 cm",
    subject: "Landscape",
    series: "Walks",
    image: "assets/paintings/sea-wildflowers.jpg",
    hero:  "assets/paintings-hero/sea-wildflowers.jpg",
    thumb: "assets/paintings-thumb/sea-wildflowers.jpg",
    detail: "assets/paintings/sea-wildflowers.jpg",
    square: "assets/paintings/sea-wildflowers.jpg",
    details: [
      "assets/paintings-detail/sea-wildflowers-1.jpg",
      "assets/paintings-detail/sea-wildflowers-2.jpg",
      "assets/paintings-detail/sea-wildflowers-3.jpg",
    ],
    available: false,
    note: "Some days arrive without weight. The sky is doing something simple and generous, the flowers don't know they're beautiful, and the sea is just there, being the sea. I painted this from a feeling more than a place — the feeling of a day that asks nothing of you.",
  },
  {
    slug: "daisies-in-glass",
    number: 2,
    title: "Three Daisies",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "30 × 40 cm",
    subject: "Still Life",
    series: "Pigment Studies",
    image: "assets/paintings/daisies.JPG",
    hero:  "assets/paintings-hero/daisies.jpg",
    thumb: "assets/paintings-thumb/daisies.jpg",
    detail: "assets/paintings/daisies.JPG",
    square: "assets/paintings/daisies.JPG",
    details: [
      "assets/paintings-detail/daisies-1.jpg",
      "assets/paintings-detail/daisies-2.jpg",
      "assets/paintings-detail/daisies-3.jpg",
    ],
    available: false,
    note: "I picked them on a walk and put them in the nearest thing — a glass bottle from the kitchen. They lasted three days. I spent those three days just looking, noticing how the light passed through the water, how the stems bent, how the white of a daisy is never only white. Painting them was a way of keeping them.",
  },
  {
    slug: "yellow-branches",
    number: 1,
    title: "Golden Blossoms",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "50 × 40 cm",
    subject: "Still Life",
    series: "Pigment Studies",
    image: "assets/paintings/yellow-branches.jpg",
    hero:  "assets/paintings-hero/yellow-branches.jpg",
    thumb: "assets/paintings-thumb/yellow-branches.jpg",
    detail: "assets/paintings/yellow-branches.jpg",
    square: "assets/paintings/yellow-branches.jpg",
    details: [
      "assets/paintings-detail/yellow-branches-1.jpg",
      "assets/paintings-detail/yellow-branches-2.jpg",
      "assets/paintings-detail/yellow-branches-3.jpg",
    ],
    available: false,
    note: "They were cut from a tree in the garden just as the buds were opening — that precise moment before full bloom, when everything is still becoming. I've always felt more moved by beginnings than by arrival. The yellow was almost too much. I kept it anyway.",
  },
];

const SERIES = [
  { slug: "portraits", title: "Portraits", count: 11, years: "2024 — present",
    summary: "Painted from life over multiple sittings. Grisaille underpainting, warm half-tones, the kind of slow looking only a willing sitter allows." },
  { slug: "light-studies", title: "Light Studies", count: 6, years: "2024 — present",
    summary: "Figures and objects under single sources — candle, window, lamp. One light; everything else is answer." },
  { slug: "walks", title: "Walks", count: 14, years: "2024 — present",
    summary: "Landscapes carried home from trips and long afternoons. Small panels on site; larger canvases finished in the studio." },
  { slug: "pigment-studies", title: "Pigment Studies", count: 5, years: "2024 — present",
    summary: "One-colour or two-colour studies, mostly still life. An exercise in how far a single tube will stretch before the eye needs help." },
];

window.PAINTINGS = PAINTINGS;
window.SERIES = SERIES;
