// data.js — shared painting data
// Artist: Somaye Minaei · signed "S. Minaei"
const PAINTINGS = [
  {
    slug: "candle-veil",
    number: 7,
    title: "Candle, Veiled",
    year: 2024,
    medium: "Oil on linen",
    dimensions: "16 × 20 in.",
    subject: "Portrait Studies",
    series: "Light Studies",
    image: "../../assets/paintings/candle-veil.jpg",
    thumb: "../../assets/paintings/candle-veil.jpg",
    detail: "../../assets/paintings/candle-veil.jpg",
    square: "../../assets/paintings/candle-veil.jpg",
    available: true,
    price: "$3,400",
    note: "A single candle held close to the face, a saffron-coloured veil pulled over the hair. I painted this over four evenings — only at night, only by the same candle. The warm light eats the shadow side; the cool side keeps its blue. I wanted the flame to feel like the true subject and the face to feel like its answer.",
    progress: [
      "Dark ground — ivory black thinned with walnut oil",
      "Warm underpainting — burnt sienna and yellow ochre on the lit side",
      "Cool shadow — ultramarine glazed into the brown",
      "Flame last — lead white over a single transparent yellow",
    ],
  },
  {
    slug: "floral-shirt",
    number: 6,
    title: "Portrait in a Floral Shirt",
    year: 2024,
    medium: "Oil on linen",
    dimensions: "20 × 24 in.",
    subject: "Portrait Studies",
    series: "Portraits",
    image: "../../assets/paintings/floral-shirt.jpg",
    thumb: "../../assets/paintings/floral-shirt.jpg",
    detail: "../../assets/paintings/floral-shirt.jpg",
    square: "../../assets/paintings/floral-shirt.jpg",
    available: true,
    price: "$3,800",
    note: "A portrait made over six Sunday sittings. The shirt is the one she always wears — the small roses gave me somewhere to rest my eye between the hours spent on the face. I kept the background warm and deep so the teal of the shirt would do the talking.",
    progress: [
      "Grisaille underpainting for the face",
      "Warm mid-tones in the hair and skin",
      "Shirt painted wet-into-wet in a single session",
      "Floral pattern last — tiny marks, no drawing",
    ],
  },
  {
    slug: "monument-valley",
    number: 5,
    title: "Monument Valley, Afternoon",
    year: 2023,
    medium: "Oil on linen",
    dimensions: "16 × 20 in.",
    subject: "Landscape",
    series: "Walks",
    image: "../../assets/paintings/monument-valley.jpg",
    thumb: "../../assets/paintings/monument-valley.jpg",
    detail: "../../assets/paintings/monument-valley.jpg",
    square: "../../assets/paintings/monument-valley.jpg",
    available: true,
    price: "$2,600",
    note: "Painted from a week spent in the southwest. I made small panels on site and finished this larger canvas in the studio. The red of the rock and the blue of the sky are nearly complementary — the whole painting is about the quiet fight between them.",
  },
  {
    slug: "yellow-branches",
    number: 4,
    title: "Yellow Branches in a Stone Vase",
    year: 2024,
    medium: "Oil on linen",
    dimensions: "12 × 16 in.",
    subject: "Still Life",
    series: "Pigment Studies",
    image: "../../assets/paintings/yellow-branches.jpg",
    thumb: "../../assets/paintings/yellow-branches.jpg",
    detail: "../../assets/paintings/yellow-branches.jpg",
    square: "../../assets/paintings/yellow-branches.jpg",
    available: true,
    price: "$1,800",
    note: "A study in cadmium yellow and cool grey. The branches came from a friend's garden at the end of winter. I let the background drift from warm to cool across the canvas — a quiet seasonal edge behind the vase.",
  },
  {
    slug: "sea-wildflowers",
    number: 3,
    title: "Sea, with Wildflowers",
    year: 2023,
    medium: "Oil on panel",
    dimensions: "10 × 14 in.",
    subject: "Landscape",
    series: "Walks",
    image: "../../assets/paintings/sea-wildflowers.jpg",
    thumb: "../../assets/paintings/sea-wildflowers.jpg",
    detail: "../../assets/paintings/sea-wildflowers.jpg",
    square: "../../assets/paintings/sea-wildflowers.jpg",
    available: true,
    price: "$1,400",
    note: "Painted on the coast, June. The far shore is barely a line. Most of the panel is sky and water; the flowers at the foot are the reward for sitting still long enough.",
  },
  {
    slug: "tree-on-rock",
    number: 2,
    title: "Tree on a Rock",
    year: 2022,
    medium: "Oil on panel",
    dimensions: "9 × 12 in.",
    subject: "Landscape",
    series: "Walks",
    image: "../../assets/paintings/tree-on-rock.jpg",
    thumb: "../../assets/paintings/tree-on-rock.jpg",
    detail: "../../assets/paintings/tree-on-rock.jpg",
    square: "../../assets/paintings/tree-on-rock.jpg",
    available: false,
    note: "An early panel. A single tree holding onto its stone, a high sky. I painted this the summer I decided painting was the thing.",
  },
];

const SERIES = [
  { slug: "portraits", title: "Portraits", count: 11, years: "2022 — present",
    summary: "Painted from life over multiple sittings. Grisaille underpainting, warm half-tones, the kind of slow looking only a willing sitter allows." },
  { slug: "light-studies", title: "Light Studies", count: 6, years: "2023 — present",
    summary: "Figures and objects under single sources — candle, window, lamp. One light; everything else is answer." },
  { slug: "walks", title: "Walks", count: 14, years: "2021 — present",
    summary: "Landscapes carried home from trips and long afternoons. Small panels on site; larger canvases finished in the studio." },
  { slug: "pigment-studies", title: "Pigment Studies", count: 5, years: "2022 — present",
    summary: "One-colour or two-colour studies, mostly still life. An exercise in how far a single tube will stretch before the eye needs help." },
];

window.PAINTINGS = PAINTINGS;
window.SERIES = SERIES;
